### ISSUE TITLE
Fail to build with Vite on Github Actions

### ISSUE THREAD

**Issue by VinhVTHE181750** [react-restart/ui#106]
## Describe the bug

Vite fails to build with @restart/ui version 1.7.0 on Github Actions. (It does build locally, but not on Github Actions)
I can confirm by downgrading to 1.6.9, which worked perfectly.

## To Reproduce

1. Update @restart/ui to 1.7.0
2. Vite will now fail to build a ReactJS app with error:

## Reproducible Example

The error is `[vite]: Rollup failed to resolve import "@restart/ui/Anchor" from "/home/runner/work/mJOB/mJOB/client/node_modules/react-bootstrap/esm/AlertLink.js".`
When I try to suppress the error by using the build.rollupOptions for that specific component, another error just pops up, for example @restart/ui/Button.

## Expected behavior

Vite build should work.

## Screenshots
![image](https://github.com/user-attachments/assets/c349bbff-8e24-4a99-a3f4-026457f3c3f8)

## Environment (please complete the following information)
- Operating System: ubuntu-latest (specified in https://github.com/VinhVTHE181750/mJOB/blob/main/.github/workflows/BuildReactJS.yml)
- Browser, Version: N/A
- react-overlays Version: none

## Additional context
Link to build logs: https://github.com/VinhVTHE181750/mJOB/actions/workflows/BuildReactJS.yml

**Comment by salimkanoun** [comment]
Same error here

**Comment by cscanlin** [comment]
Almost certainly related to the release a couple hours ago:
https://www.npmjs.com/package/@restart/ui?activeTab=versions

Pinning this in your dependencies should almost certainly work around the issue (I'm trying it now):
```
"@restart/ui": "1.6.9",
```

**Comment by kyletsang** [comment]
Proxy directories are placed in the wrong folder in the build output.  Checking now

**Comment by kyletsang** [comment]
Try 1.8.0
