### ISSUE TITLE
Dropdown: onToggle not called when rendering Anchor in DropdownItem

### ISSUE THREAD

**Issue by kyletsang** [react-restart/ui#24]
Saw this when converting dropdowns in RB.

When rendering an anchor as the component for `DropdownItem`, `preventDefault` is called in the click handler since the anchor has `href="#"` by default:
https://github.com/react-restart/ui/blob/fd8f5b79190d1109a32f93d0db0c649048b425b9/src/Button.tsx#L64-L66

Unfortunately, this prevents `onToggle` from being called in `Dropdown`:
https://github.com/react-restart/ui/blob/fd8f5b79190d1109a32f93d0db0c649048b425b9/src/Dropdown.tsx#L190-L192

Previous RB behavior implemented the ignored `preventDefault` and `stopPropagation`, so `onToggle` was always called.  The ability to stop `onToggle` from being triggered in `onSelect` makes sense.  Not sure which approach I should take on this in RB though since we should allow anchors for dropdown items.

Thoughts on this @jquense?

**Comment by jquense** [comment]
huh that is tricky. I guess we are overloading the meaning of "prevent default" I think we should revert to the original behavior since `onToggle` can manually be prevented at the dropdown level? How does that sound?

**Comment by kyletsang** [comment]
Yeah that should work.  Thanks!
