### ISSUE TITLE
ModalManager: Unit test are failing on MacBook Pro (15-inch, 2016)

### ISSUE THREAD

**Issue by marcalexiei** [react-restart/ui#48]
## Describe the bug

Unit test of `ModalManager` are failing:

## To Reproduce

1. Clone the repository
2. Follow setup instructions
3. Run `yarn tdd`

## Reproducible Example

N/A

## Expected behavior

Unit tests run without errors

## Screenshots

<img width="921" alt="image" src="https://user-images.githubusercontent.com/24919330/152593134-e5bd8090-8056-4df5-bc12-4ba97a1602bd.png">

## Environment (please complete the following information)

- Device: MacBook Pro (15-inch, 2016)
- Operating System: Mac OS 10.15.7
- Browser, Version: Chrome 97.0.4692.99
- ui/restart 1.0.1

## Additional context

A similar error happens also on React Bootstrap and is reported in [this issue](https://github.com/react-bootstrap/react-bootstrap/issues/6087)

After a little investigation I found that the issue may be caused by the [following line](https://github.com/react-restart/ui/blob/1aeaaf378699ce5dd19c0543c21e95a88909b06f/src/ModalManager.ts#L79):
```typescript
 if (containerState.scrollBarWidth) { /* set styles on container */ }
```

On my machine `containerState.scrollBarWidth` is set to `0` so this block is skipped  and styles are not set on `<body/>` element causing the above errors.

I'll investigate a little further and then I'll open a PR.
Hopefully this will also fix the issue on react-bootstrap side.

**Comment by marcalexiei** [comment]
On MacOS by default scrollbars are hidden. See System Preferences -> General:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/24919330/152614401-b093c2ab-2912-41c6-95ef-6b1727daa060.png">

This cause `getBodyScrollbarWidth` to return `0` so above condition on `ModalManager.setContainerStyle` is set to 0.
Setting "Show scroll bars" option to "always" solves the issue.

**Comment by jquense** [comment]
Yeah this is unfortunately something we can fix without ending up making the test ineffective. Thanks for taking a look
