### ISSUE TITLE
SelectCallback should allow numbers

### ISSUE THREAD

**Issue by brennie** [react-restart/ui#70]
SelectCallback is of type `(a: string | null) => void` but eventKeys can also be numbers.

I'm currently working around this with a function with the signature `(a: string | number | null) => void`.

**Comment by kyletsang** [comment]
The code transforms all event keys to strings here: https://github.com/react-restart/ui/blob/7ecc1a6d8417d28f0463727db8c086ede432aaf3/src/SelectableContext.tsx#L6

Strings are preferred for event keys and I think we allowed numbers for backwards compatibility.
