### ISSUE TITLE
A type error occurs when specifying a Link component of `next/link` or a component of type `React.ElementType` in the `as` props of the `Button` component

### ISSUE THREAD

**Issue by odanado** [react-restart/ui#94]
## Describe the bug

A type error occurs when specifying a Link component of `next/link` or a component of type `React.ElementType` in the `as` props of the `Button` component.

Here is a repository that reproduces this error.
https://github.com/odan-sandbox/react-restart-next-link-sandbox/blob/eed93939ed6437f925e57c99b6e32f9949dc0492/src/pages/index.tsx#L7-L14

Here is the log from running `npx tsc --noEmit`.

```shell
❯ npx tsc --noEmit
src/pages/index.tsx:9:15 - error TS2322: Type 'ForwardRefExoticComponent<Omit<AnchorHTMLAttributes<HTMLAnchorElement>, keyof InternalLinkProps> & InternalLinkProps & { ...; } & RefAttributes<...>>' is not assignable to type 'keyof IntrinsicElements | undefined'.

9       <Button as={Link}></Button>
                ~~

  node_modules/@restart/ui/esm/Button.d.ts:38:5
    38     as?: keyof JSX.IntrinsicElements | undefined;
           ~~
    The expected type comes from property 'as' which is declared here on type 'IntrinsicAttributes & ButtonProps & RefAttributes<HTMLElement>'

src/pages/index.tsx:10:15 - error TS2322: Type 'FunctionComponent<any>' is not assignable to type 'keyof IntrinsicElements | undefined'.

10       <Button as={MyLink}></Button>
                 ~~

  node_modules/@restart/ui/esm/Button.d.ts:38:5
    38     as?: keyof JSX.IntrinsicElements | undefined;
           ~~
    The expected type comes from property 'as' which is declared here on type 'IntrinsicAttributes & ButtonProps & RefAttributes<HTMLElement>'


Found 2 errors in the same file, starting at: src/pages/index.tsx:9
```

These type errors do not occur in `NavItem` components.

## To Reproduce

1. `git clone https://github.com/odan-sandbox/react-restart-next-link-sandbox`
2. `cd react-restart-next-link-sandbox`
3. `npm i`
4. `npx tsc --noEmit`

## Reproducible Example
https://github.com/odan-sandbox/react-restart-next-link-sandbox

## Expected behavior

As with the `NavItem` component, no type errors occur with the `Button` component.

## Screenshots
None.

## Environment (please complete the following information)

- @restart/ui: 1.6.6

## Additional context
None.

**Comment by jquense** [comment]
that is correct, you can only set "host" elements, e.g. DOM elements, in `as` , you should instead wrap `Link` around `Button` with `passHref`

**Comment by odanado** [comment]
I see. I have verified that the following code works as intended.
```jsx
      <Link href="" passHref legacyBehavior>
        <Button as="a">link</Button>
      </Link>
```

However, since it requires the legacyBehavior option, it may not work in future versions of Next.js.
